notifications:
  email: false
sudo: false
language: python
cache:
  - pip
python:
  - '3.6'
  - '3.7'

before_install:
  - travis_retry pip install --upgrade pip setuptools py
  - travis_retry curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python - --version 0.12.16;
    source $HOME/.poetry/env;

install:
  - travis_retry poetry install

script:
  - "./run-tests.sh"

deploy:
  - provider: script
    skip_cleanup: true
    script: cd $TRAVIS_BUILD_DIR; ./build-docker-backend-image.sh
    on:
      all_branches: true
      condition: $SUITE = integration && $TRAVIS_BRANCH =~ ^master|prod$
  - provider: script
    skip_cleanup: true
    script: cd $TRAVIS_BUILD_DIR; ./build-docker-ui-image.sh
    on:
      all_branches: true
      condition: $SUITE = ui && $TRAVIS_BRANCH =~ ^master|prod$