# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 CERN.
#
# inspirehep is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.

version: '2.1'
services:
  disambiguation:
    restart: "always"
    build: .
    environment:
      - "DISAMBIGUATION_LOG_LEVEL=INFO"
      - "DISAMBIGUATION_ES_HOSTNAME=localhost:9200"
      - "DISAMBIGUATION_REDIS_URL=redis://localhost:6379/0"
      - "DISAMBIGUATION_SAMPLED_PAIRS_SIZE=12000000"
      - "DISAMBIGUATION_CLUSTERING_N_JOBS=8"
    command: poetry run inspire-disambiguation cluster